name: task_tracker_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
#  flutter_web_auth: ^0.5.0
#  oauth2: ^2.0.2
  path_provider: ^2.0.9
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  percent_indicator: ^4.2.3
  calendar_date_picker2: ^1.0.6
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_bloc: ^8.1.6
  permission_handler: ^11.3.1
  flutter_colorpicker: ^1.1.0
  intl: ^0.19.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  drag_and_drop_lists:
    git:
      url: https://github.com/arsarsars1/drag_and_drop_lists.git
      ref: test

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.7
  flutter_lints: ^4.0.0
  json_serializable: ^6.0.0

flutter:

  uses-material-design: true
